### ISSUE TITLE
PointList.add_point() is very slow

### ISSUE THREAD

**Issue by sezelt** [bsavitzky/py4DSTEM#5]
In the initial notebooks we've been using, we add points to a pointlist by looping through and adding one at a time:
```python
 for i in range(length):
    new_point = (max_point_indices_x[i],max_point_indices_y[i],point_intensities[i])
    point_list.add_point(new_point)
```
This is **really** slow if you are doing phase-ier correlation rather than usual nearly-cross hybrid and so have a lot of points to add. Perhaps make it possible to initialize the points data array with zeros so you're not concatenating every time?
Or make it more friendly to set the data from a numpy array. The present `add_dataarray` method is clumsy because you have to make a structured array. And if you naïvely (as I did) just try passing a regular old numpy array, everything gets wonky.
For the stuff I was running, not looping thru one-by-one took me down from 30s/DP to <1s.

**Comment by bsavitzky** [comment]
Hey Steven,

Thanks, you're right, this is a slow operation, and the PointList syntax is
generally not the cleanest.  There is a method for this -
PointList.add_tuple_of_nparrays(data) - which expects the input data to be
a tuple, of length equal to the number of pointlist coordinates, and where
each element of the tuple is a 1D np array of your data.  The reasoning
behind this clumsy approach, rather than accepting simple numpy arrays, was
to make sure the arrays get mapped to the proper coordinates.  But as long
as you make sure your 2D np arrays are in the right order, this shouldn't
be a problem, so I've gone ahead and added a method to take regular old
numpy arrays.  Try using PointList.add_unstructured_dataarray(data).  It
just takes your array, converts it to a structured array, then adds that,
so it should be much faster.

Ben

**Comment by bsavitzky** [comment]
One other quick note: this routine is currently just in the dev branch.
This will all get pushed to master next week, but if you'd like to use this
routine now, you can find it in dev.
